name: Publish NuGet Package

on:
  push:
    branches:
      - main  # Runs on main branch pushes
    tags:
      - 'v*'  # Also runs when a version tag is pushed

jobs:
  publish:
    name: Build and Publish NuGet Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Change if needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Extract version from .csproj
        id: version
        run: echo "VERSION=$(grep -oPm1 '(?<=<Version>)[^<]+' *.csproj)" >> $GITHUB_ENV

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet Package (Addikted.BetterEventSystem)
        run: dotnet pack --configuration Release -p:PackageId=Addikted.BetterEventSystem --no-build --output .

      - name: Pack NuGet Package (BetterEventSystem)
        run: dotnet pack --configuration Release -p:PackageId=BetterEventSystem --no-build --output .

      - name: Publish Addikted.BetterEventSystem to NuGet
        run: dotnet nuget push Addikted.BetterEventSystem.${{ env.VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Publish BetterEventSystem to NuGet
        run: dotnet nuget push BetterEventSystem.${{ env.VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
